import 'dart:ui';
import 'package:vector_math/vector_math_64.dart';
import 'point_cloud.dart';

/// Represents a vertex in a 3D mesh
class MeshVertex {
  final Vector3 position;
  final Vector3? normal;
  final Vector2? texCoord;
  final Color? color;

  MeshVertex({
    required this.position,
    this.normal,
    this.texCoord,
    this.color,
  });

  Map<String, dynamic> toJson() => {
        'x': position.x,
        'y': position.y,
        'z': position.z,
        if (normal != null) 'nx': normal!.x,
        if (normal != null) 'ny': normal!.y,
        if (normal != null) 'nz': normal!.z,
        if (texCoord != null) 'u': texCoord!.x,
        if (texCoord != null) 'v': texCoord!.y,
        if (color != null) 'r': (color!.r * 255).round(),
        if (color != null) 'g': (color!.g * 255).round(),
        if (color != null) 'b': (color!.b * 255).round(),
      };
}

/// Represents a triangle face in a 3D mesh
class MeshFace {
  final int v1; // Vertex index 1
  final int v2; // Vertex index 2
  final int v3; // Vertex index 3

  MeshFace(this.v1, this.v2, this.v3);

  Map<String, dynamic> toJson() => {
        'v1': v1,
        'v2': v2,
        'v3': v3,
      };
}

/// Represents a complete 3D mesh with vertices, faces, and optional texture
class MeshModel {
  final List<MeshVertex> vertices;
  final List<MeshFace> faces;
  final DateTime createdAt;
  final String method; // 'poisson', 'ball_pivot', 'marching_cubes', 'huawei', etc.
  final Map<String, dynamic> metadata;
  final String? texturePath; // Path to texture image if available

  MeshModel({
    required this.vertices,
    required this.faces,
    DateTime? createdAt,
    required this.method,
    Map<String, dynamic>? metadata,
    this.texturePath,
  })  : createdAt = createdAt ?? DateTime.now(),
        metadata = metadata ?? {};

  /// Calculate bounding box of the mesh
  ({Vector3 min, Vector3 max}) getBoundingBox() {
    if (vertices.isEmpty) {
      return (min: Vector3.zero(), max: Vector3.zero());
    }

    double minX = vertices.first.position.x;
    double minY = vertices.first.position.y;
    double minZ = vertices.first.position.z;
    double maxX = vertices.first.position.x;
    double maxY = vertices.first.position.y;
    double maxZ = vertices.first.position.z;

    for (final vertex in vertices) {
      minX = minX < vertex.position.x ? minX : vertex.position.x;
      minY = minY < vertex.position.y ? minY : vertex.position.y;
      minZ = minZ < vertex.position.z ? minZ : vertex.position.z;
      maxX = maxX > vertex.position.x ? maxX : vertex.position.x;
      maxY = maxY > vertex.position.y ? maxY : vertex.position.y;
      maxZ = maxZ > vertex.position.z ? maxZ : vertex.position.z;
    }

    return (
      min: Vector3(minX, minY, minZ),
      max: Vector3(maxX, maxY, maxZ),
    );
  }

  /// Get center point of the mesh
  Vector3 getCenter() {
    final bbox = getBoundingBox();
    return (bbox.min + bbox.max) / 2;
  }

  /// Convert to point cloud (sample vertices)
  PointCloud toPointCloud() {
    final points = vertices.map((v) => Point3D(
          position: v.position,
          color: v.color ?? const Color(0xFFCCCCCC),
          confidence: 1.0,
        )).toList();

    return PointCloud(
      points: points,
      method: 'mesh_to_pointcloud',
      metadata: {'source_method': method, ...metadata},
    );
  }

  /// Export to OBJ format (Wavefront Object)
  String toOBJ() {
    final buffer = StringBuffer();

    // OBJ header
    buffer.writeln('# Generated by AncientVision');
    buffer.writeln('# Method: $method');
    buffer.writeln('# Created: ${createdAt.toIso8601String()}');
    buffer.writeln('# Vertices: ${vertices.length}');
    buffer.writeln('# Faces: ${faces.length}');
    buffer.writeln();

    // Vertices
    for (final vertex in vertices) {
      buffer.writeln(
        'v ${vertex.position.x.toStringAsFixed(6)} '
        '${vertex.position.y.toStringAsFixed(6)} '
        '${vertex.position.z.toStringAsFixed(6)}',
      );
    }
    buffer.writeln();

    // Normals (if available) - write for ALL vertices to keep indices aligned
    final hasNormals = vertices.any((v) => v.normal != null);
    if (hasNormals) {
      for (final vertex in vertices) {
        final n = vertex.normal ?? Vector3(0, 1, 0);
        buffer.writeln(
          'vn ${n.x.toStringAsFixed(6)} '
          '${n.y.toStringAsFixed(6)} '
          '${n.z.toStringAsFixed(6)}',
        );
      }
      buffer.writeln();
    }

    // Texture coordinates (if available) - write for ALL vertices to keep indices aligned
    final hasTexCoords = vertices.any((v) => v.texCoord != null);
    if (hasTexCoords) {
      for (final vertex in vertices) {
        final tc = vertex.texCoord ?? Vector2(0, 0);
        buffer.writeln(
          'vt ${tc.x.toStringAsFixed(6)} '
          '${tc.y.toStringAsFixed(6)}',
        );
      }
      buffer.writeln();
    }

    // Faces (OBJ uses 1-based indexing)
    for (final face in faces) {
      if (hasNormals && hasTexCoords) {
        buffer.writeln('f ${face.v1 + 1}/${face.v1 + 1}/${face.v1 + 1} '
            '${face.v2 + 1}/${face.v2 + 1}/${face.v2 + 1} '
            '${face.v3 + 1}/${face.v3 + 1}/${face.v3 + 1}');
      } else if (hasNormals) {
        buffer.writeln('f ${face.v1 + 1}//${face.v1 + 1} '
            '${face.v2 + 1}//${face.v2 + 1} '
            '${face.v3 + 1}//${face.v3 + 1}');
      } else if (hasTexCoords) {
        buffer.writeln('f ${face.v1 + 1}/${face.v1 + 1} '
            '${face.v2 + 1}/${face.v2 + 1} '
            '${face.v3 + 1}/${face.v3 + 1}');
      } else {
        buffer.writeln('f ${face.v1 + 1} ${face.v2 + 1} ${face.v3 + 1}');
      }
    }

    return buffer.toString();
  }

  /// Export to PLY format with face data
  String toPLY() {
    final buffer = StringBuffer();

    // PLY header
    buffer.writeln('ply');
    buffer.writeln('format ascii 1.0');
    buffer.writeln('comment Generated by AncientVision');
    buffer.writeln('comment Method: $method');
    buffer.writeln('comment Created: ${createdAt.toIso8601String()}');
    buffer.writeln('element vertex ${vertices.length}');
    buffer.writeln('property float x');
    buffer.writeln('property float y');
    buffer.writeln('property float z');

    final hasNormals = vertices.any((v) => v.normal != null);
    if (hasNormals) {
      buffer.writeln('property float nx');
      buffer.writeln('property float ny');
      buffer.writeln('property float nz');
    }

    final hasColors = vertices.any((v) => v.color != null);
    if (hasColors) {
      buffer.writeln('property uchar red');
      buffer.writeln('property uchar green');
      buffer.writeln('property uchar blue');
    }

    buffer.writeln('element face ${faces.length}');
    buffer.writeln('property list uchar int vertex_indices');
    buffer.writeln('end_header');

    // Vertex data
    for (final vertex in vertices) {
      final parts = <String>[
        vertex.position.x.toStringAsFixed(6),
        vertex.position.y.toStringAsFixed(6),
        vertex.position.z.toStringAsFixed(6),
      ];

      if (hasNormals) {
        final n = vertex.normal ?? Vector3(0, 1, 0);
        parts.addAll([
          n.x.toStringAsFixed(6),
          n.y.toStringAsFixed(6),
          n.z.toStringAsFixed(6),
        ]);
      }

      if (hasColors) {
        final c = vertex.color ?? const Color(0xFFCCCCCC);
        parts.addAll([
          '${(c.r * 255).round()}',
          '${(c.g * 255).round()}',
          '${(c.b * 255).round()}',
        ]);
      }

      buffer.writeln(parts.join(' '));
    }

    // Face data
    for (final face in faces) {
      buffer.writeln('3 ${face.v1} ${face.v2} ${face.v3}');
    }

    return buffer.toString();
  }

  Map<String, dynamic> toJson() => {
        'vertices': vertices.map((v) => v.toJson()).toList(),
        'faces': faces.map((f) => f.toJson()).toList(),
        'createdAt': createdAt.toIso8601String(),
        'method': method,
        'metadata': metadata,
        'texturePath': texturePath,
        'vertexCount': vertices.length,
        'faceCount': faces.length,
      };
}
