import 'dart:ui';
import 'package:vector_math/vector_math_64.dart';

/// Represents a 3D point in space with color information
class Point3D {
  final Vector3 position;
  final Color color;
  final double confidence; // 0.0 to 1.0
  final Vector3? normal; // Surface normal at this point

  Point3D({
    required this.position,
    required this.color,
    this.confidence = 1.0,
    this.normal,
  });

  Map<String, dynamic> toJson() => {
        'x': position.x,
        'y': position.y,
        'z': position.z,
        'r': (color.r * 255).round(),
        'g': (color.g * 255).round(),
        'b': (color.b * 255).round(),
        'a': (color.a * 255).round(),
        'confidence': confidence,
        if (normal != null) 'nx': normal!.x,
        if (normal != null) 'ny': normal!.y,
        if (normal != null) 'nz': normal!.z,
      };

  factory Point3D.fromJson(Map<String, dynamic> json) => Point3D(
        position: Vector3(
          json['x'] as double,
          json['y'] as double,
          json['z'] as double,
        ),
        color: Color.fromARGB(
          (json['a'] is double ? (json['a'] as double).round() : json['a'] as int),
          (json['r'] is double ? (json['r'] as double).round() : json['r'] as int),
          (json['g'] is double ? (json['g'] as double).round() : json['g'] as int),
          (json['b'] is double ? (json['b'] as double).round() : json['b'] as int),
        ),
        confidence: json['confidence'] as double? ?? 1.0,
        normal: json['nx'] != null
            ? Vector3(
                json['nx'] as double,
                json['ny'] as double,
                json['nz'] as double,
              )
            : null,
      );
}

/// Represents a sparse or dense 3D point cloud
class PointCloud {
  final List<Point3D> points;
  final DateTime createdAt;
  final String method; // 'sparse_sfm', 'dense_mvs', 'huawei', etc.
  final Map<String, dynamic> metadata;

  PointCloud({
    required this.points,
    DateTime? createdAt,
    required this.method,
    Map<String, dynamic>? metadata,
  })  : createdAt = createdAt ?? DateTime.now(),
        metadata = metadata ?? {};

  /// Calculate bounding box of the point cloud
  ({Vector3 min, Vector3 max}) getBoundingBox() {
    if (points.isEmpty) {
      return (min: Vector3.zero(), max: Vector3.zero());
    }

    double minX = points.first.position.x;
    double minY = points.first.position.y;
    double minZ = points.first.position.z;
    double maxX = points.first.position.x;
    double maxY = points.first.position.y;
    double maxZ = points.first.position.z;

    for (final point in points) {
      minX = minX < point.position.x ? minX : point.position.x;
      minY = minY < point.position.y ? minY : point.position.y;
      minZ = minZ < point.position.z ? minZ : point.position.z;
      maxX = maxX > point.position.x ? maxX : point.position.x;
      maxY = maxY > point.position.y ? maxY : point.position.y;
      maxZ = maxZ > point.position.z ? maxZ : point.position.z;
    }

    return (
      min: Vector3(minX, minY, minZ),
      max: Vector3(maxX, maxY, maxZ),
    );
  }

  /// Get center point of the point cloud
  Vector3 getCenter() {
    final bbox = getBoundingBox();
    return (bbox.min + bbox.max) / 2;
  }

  /// Export to PLY format (Stanford Polygon File Format)
  String toPLY() {
    final buffer = StringBuffer();

    // PLY header
    buffer.writeln('ply');
    buffer.writeln('format ascii 1.0');
    buffer.writeln('comment Generated by AncientVision');
    buffer.writeln('comment Method: $method');
    buffer.writeln('comment Created: ${createdAt.toIso8601String()}');
    buffer.writeln('element vertex ${points.length}');
    buffer.writeln('property float x');
    buffer.writeln('property float y');
    buffer.writeln('property float z');
    buffer.writeln('property uchar red');
    buffer.writeln('property uchar green');
    buffer.writeln('property uchar blue');
    buffer.writeln('property float confidence');
    buffer.writeln('end_header');

    // Point data
    for (final point in points) {
      buffer.writeln(
        '${point.position.x.toStringAsFixed(6)} '
        '${point.position.y.toStringAsFixed(6)} '
        '${point.position.z.toStringAsFixed(6)} '
        '${(point.color.r * 255).round()} '
        '${(point.color.g * 255).round()} '
        '${(point.color.b * 255).round()} '
        '${point.confidence.toStringAsFixed(4)}',
      );
    }

    return buffer.toString();
  }

  /// Import from PLY format
  static PointCloud fromPLY(String plyContent) {
    final lines = plyContent.split('\n');
    final points = <Point3D>[];

    // Find end of header
    int headerEnd = 0;
    int vertexCount = 0;

    for (int i = 0; i < lines.length; i++) {
      final line = lines[i].trim();
      if (line.startsWith('element vertex')) {
        vertexCount = int.parse(line.split(' ').last);
      }
      if (line == 'end_header') {
        headerEnd = i + 1;
        break;
      }
    }

    // Parse vertex data
    for (int i = headerEnd; i < headerEnd + vertexCount && i < lines.length; i++) {
      final parts = lines[i].trim().split(RegExp(r'\s+'));
      if (parts.length >= 6) {
        points.add(Point3D(
          position: Vector3(
            double.parse(parts[0]),
            double.parse(parts[1]),
            double.parse(parts[2]),
          ),
          color: Color.fromARGB(
            255,
            int.parse(parts[3]),
            int.parse(parts[4]),
            int.parse(parts[5]),
          ),
          confidence: parts.length > 6 ? double.parse(parts[6]) : 1.0,
        ));
      }
    }

    return PointCloud(
      points: points,
      method: 'imported_ply',
      metadata: {'source': 'PLY file'},
    );
  }

  Map<String, dynamic> toJson() => {
        'points': points.map((p) => p.toJson()).toList(),
        'createdAt': createdAt.toIso8601String(),
        'method': method,
        'metadata': metadata,
        'pointCount': points.length,
      };

  factory PointCloud.fromJson(Map<String, dynamic> json) => PointCloud(
        points: (json['points'] as List)
            .map((p) => Point3D.fromJson(p as Map<String, dynamic>))
            .toList(),
        createdAt: DateTime.parse(json['createdAt'] as String),
        method: json['method'] as String,
        metadata: json['metadata'] as Map<String, dynamic>? ?? {},
      );
}
