import 'coin_models.dart';

/// Comprehensive period database - 40+ historical periods
class CoinPeriodDatabase {
  CoinPeriodDatabase._();

  static const Map<String, CoinPeriodInfo> periodDatabase = {
    // GREEK WORLD
    'archaic_greek': CoinPeriodInfo(
      period: 'Archaic Greek',
      dateRange: '700-480 BCE',
      characteristics: ['Thick flan', 'Incuse reverse', 'Simple designs', 'Electrum', 'Turtle', 'Lion head', 'Gorgon'],
      regions: ['Lydia', 'Ionia', 'Aegina', 'Athens', 'Corinth'],
      materials: ['Electrum', 'Silver'],
      denominations: ['Stater', 'Trite', 'Hekte', 'Hemihekte'],
      rulers: ['Croesus of Lydia', 'Various city-states'],
      weight: 0.3,
    ),
    'classical_greek': CoinPeriodInfo(
      period: 'Classical Greek',
      dateRange: '480-323 BCE',
      characteristics: ['High relief', 'Artistic excellence', 'Owl of Athens', 'Pegasus', 'Tetradrachm', 'Arethusa', 'Chariot'],
      regions: ['Athens', 'Corinth', 'Syracuse', 'Macedonia', 'Thebes', 'Aegina'],
      materials: ['Silver', 'Gold', 'Bronze'],
      denominations: ['Tetradrachm', 'Drachm', 'Didrachm', 'Stater', 'Obol', 'Hemiobol'],
      rulers: ['Philip II', 'Various poleis'],
      weight: 0.35,
    ),
    'hellenistic': CoinPeriodInfo(
      period: 'Hellenistic',
      dateRange: '323-31 BCE',
      characteristics: ['Royal portraits', 'Larger flans', 'Alexander types', 'Elephant', 'Zeus', 'Heracles', 'Eagle'],
      regions: ['Ptolemaic Egypt', 'Seleucid Empire', 'Macedon', 'Bactria', 'Pergamon', 'Pontus'],
      materials: ['Silver', 'Gold', 'Bronze'],
      denominations: ['Tetradrachm', 'Drachm', 'Stater', 'Oktadrachm', 'Dekadrachm'],
      rulers: ['Alexander the Great', 'Ptolemy I-XV', 'Seleucus I', 'Antiochus', 'Mithridates VI'],
      weight: 0.35,
    ),

    // ROMAN WORLD
    'roman_republic': CoinPeriodInfo(
      period: 'Roman Republic',
      dateRange: '280-27 BCE',
      characteristics: ['Denarius', 'Roma head', 'Dioscuri', 'Quadriga', 'Janus', 'Prow', 'Victory'],
      regions: ['Rome', 'Italy', 'Spain', 'Sicily', 'Greece'],
      materials: ['Silver', 'Bronze', 'Gold'],
      denominations: ['Denarius', 'Quinarius', 'Sestertius', 'As', 'Semis', 'Triens', 'Quadrans', 'Aureus'],
      rulers: ['Sulla', 'Pompey', 'Julius Caesar', 'Brutus', 'Mark Antony'],
      weight: 0.4,
    ),
    'roman_imperial_julio_claudian': CoinPeriodInfo(
      period: 'Julio-Claudian Dynasty',
      dateRange: '27 BCE - 68 CE',
      characteristics: ['Emperor portraits', 'Laureate head', 'Aureus', 'Denarius', 'Sestertius', 'SPQR'],
      regions: ['Roman Empire'],
      materials: ['Gold', 'Silver', 'Bronze', 'Orichalcum'],
      denominations: ['Aureus', 'Denarius', 'Sestertius', 'Dupondius', 'As', 'Semis', 'Quadrans'],
      rulers: ['Augustus', 'Tiberius', 'Caligula', 'Claudius', 'Nero'],
      weight: 0.45,
    ),
    'roman_imperial_flavian': CoinPeriodInfo(
      period: 'Flavian Dynasty',
      dateRange: '69-96 CE',
      characteristics: ['Colosseum', 'Judaea Capta', 'Military themes', 'High quality portraits'],
      regions: ['Roman Empire'],
      materials: ['Gold', 'Silver', 'Bronze', 'Orichalcum'],
      denominations: ['Aureus', 'Denarius', 'Sestertius', 'Dupondius', 'As'],
      rulers: ['Vespasian', 'Titus', 'Domitian'],
      weight: 0.45,
    ),
    'roman_imperial_adoptive': CoinPeriodInfo(
      period: 'Nerva-Antonine Dynasty',
      dateRange: '96-192 CE',
      characteristics: ['Five Good Emperors', 'Highest quality', 'Detailed portraits', 'Architectural reverses'],
      regions: ['Roman Empire'],
      materials: ['Gold', 'Silver', 'Bronze'],
      denominations: ['Aureus', 'Denarius', 'Sestertius', 'Dupondius', 'As'],
      rulers: ['Nerva', 'Trajan', 'Hadrian', 'Antoninus Pius', 'Marcus Aurelius', 'Commodus'],
      weight: 0.5,
    ),
    'roman_imperial_severan': CoinPeriodInfo(
      period: 'Severan Dynasty',
      dateRange: '193-235 CE',
      characteristics: ['Military emperors', 'Septimius Severus', 'Caracalla', 'Julia Domna'],
      regions: ['Roman Empire'],
      materials: ['Gold', 'Silver', 'Bronze'],
      denominations: ['Aureus', 'Denarius', 'Antoninianus', 'Sestertius', 'As'],
      rulers: ['Septimius Severus', 'Caracalla', 'Geta', 'Elagabalus', 'Severus Alexander'],
      weight: 0.45,
    ),
    'roman_crisis': CoinPeriodInfo(
      period: 'Crisis of Third Century',
      dateRange: '235-284 CE',
      characteristics: ['Debased silver', 'Antoninianus', 'Radiate crown', 'Rapid succession', 'Provincial mints'],
      regions: ['Roman Empire', 'Gallic Empire', 'Palmyrene Empire', 'Britannia'],
      materials: ['Billon', 'Bronze', 'Silver'],
      denominations: ['Antoninianus', 'Denarius', 'Sestertius', 'Double Sestertius'],
      rulers: ['Gordian III', 'Philip I', 'Decius', 'Gallienus', 'Claudius II', 'Aurelian', 'Probus'],
      weight: 0.35,
    ),
    'late_roman': CoinPeriodInfo(
      period: 'Late Roman Empire',
      dateRange: '284-476 CE',
      characteristics: ['Smaller modules', 'Christian symbols', 'Chi-Rho', 'Follis', 'Solidus', 'Vota'],
      regions: ['Roman Empire', 'Constantinople', 'Trier', 'Antioch', 'Alexandria'],
      materials: ['Gold', 'Bronze', 'Silver'],
      denominations: ['Solidus', 'Semissis', 'Tremissis', 'Siliqua', 'Follis', 'Nummus', 'Centenionalis'],
      rulers: ['Diocletian', 'Constantine I', 'Constantius II', 'Julian', 'Valentinian', 'Theodosius'],
      weight: 0.4,
    ),

    // BYZANTINE EMPIRE
    'early_byzantine': CoinPeriodInfo(
      period: 'Early Byzantine',
      dateRange: '491-717 CE',
      characteristics: ['Facing busts', 'Cross motifs', 'Greek legends', 'Solidus', 'Large M follis', 'Justinian'],
      regions: ['Constantinople', 'Ravenna', 'Carthage', 'Alexandria', 'Antioch'],
      materials: ['Gold', 'Bronze', 'Silver'],
      denominations: ['Solidus', 'Semissis', 'Tremissis', 'Follis', 'Half-Follis', 'Decanummium', 'Pentanummium'],
      rulers: ['Anastasius I', 'Justin I', 'Justinian I', 'Justin II', 'Maurice', 'Phocas', 'Heraclius'],
      weight: 0.4,
    ),
    'middle_byzantine': CoinPeriodInfo(
      period: 'Middle Byzantine',
      dateRange: '717-1204 CE',
      characteristics: ['Christ imagery', 'Cup-shaped (scyphate)', 'Religious themes', 'Histamenon', 'Iconoclasm'],
      regions: ['Constantinople', 'Thessalonica', 'Cherson'],
      materials: ['Gold', 'Electrum', 'Bronze', 'Silver'],
      denominations: ['Solidus', 'Histamenon', 'Tetarteron', 'Miliaresion', 'Follis'],
      rulers: ['Leo III', 'Constantine V', 'Basil I', 'Constantine VII', 'Basil II', 'Constantine IX'],
      weight: 0.4,
    ),
    'late_byzantine': CoinPeriodInfo(
      period: 'Late Byzantine',
      dateRange: '1204-1453 CE',
      characteristics: ['Debased metal', 'Small module', 'Regional mints', 'Hyperpyron', 'Latin influence'],
      regions: ['Nicaea', 'Thessalonica', 'Constantinople', 'Trebizond'],
      materials: ['Electrum', 'Silver', 'Bronze', 'Billon'],
      denominations: ['Hyperpyron', 'Aspron Trachy', 'Tetarteron', 'Stamenon', 'Tornese'],
      rulers: ['Theodore I Laskaris', 'Michael VIII', 'Andronicus II', 'John V', 'Constantine XI'],
      weight: 0.35,
    ),

    // CELTIC & BARBARIAN
    'celtic': CoinPeriodInfo(
      period: 'Celtic',
      dateRange: '300 BCE - 100 CE',
      characteristics: ['Abstract designs', 'Horse motifs', 'Geometric patterns', 'Gold staters', 'Boar', 'Chariot', 'Torc'],
      regions: ['Gaul', 'Britain', 'Danubian', 'Iberia', 'Noricum'],
      materials: ['Gold', 'Silver', 'Bronze', 'Potin'],
      denominations: ['Stater', 'Quarter Stater', 'Unit', 'Potin Unit'],
      rulers: ['Vercingetorix (Gaul)', 'Cunobelinus (Britain)', 'Various tribes'],
      weight: 0.35,
    ),
    'vandal': CoinPeriodInfo(
      period: 'Vandal Kingdom',
      dateRange: '429-534 CE',
      characteristics: ['Crude style', 'Roman imitation', 'North African'],
      regions: ['Carthage', 'North Africa'],
      materials: ['Silver', 'Bronze'],
      denominations: ['Siliqua', 'Nummi', '50 Denarii', '25 Denarii'],
      rulers: ['Gaiseric', 'Huneric', 'Gunthamund', 'Thrasamund', 'Hilderic', 'Gelimer'],
      weight: 0.25,
    ),
    'ostrogothic': CoinPeriodInfo(
      period: 'Ostrogothic Kingdom',
      dateRange: '493-553 CE',
      characteristics: ['Roman tradition', 'Theodoric', 'Ravenna mint', 'Monogram'],
      regions: ['Italy', 'Ravenna', 'Rome', 'Milan'],
      materials: ['Gold', 'Silver', 'Bronze'],
      denominations: ['Solidus', 'Tremissis', 'Half-Siliqua', 'Quarter-Siliqua', 'Nummi'],
      rulers: ['Theodoric', 'Athalaric', 'Theodahad', 'Witigis', 'Totila'],
      weight: 0.3,
    ),
    'visigothic': CoinPeriodInfo(
      period: 'Visigothic Kingdom',
      dateRange: '418-721 CE',
      characteristics: ['Tremissis gold', 'Crude portraits', 'Cross reverse', 'Iberian'],
      regions: ['Spain', 'Southern Gaul', 'Toledo', 'Seville'],
      materials: ['Gold', 'Bronze'],
      denominations: ['Tremissis', 'Semissis'],
      rulers: ['Leovigild', 'Reccared', 'Sisebut', 'Chindasuinth', 'Reccesuinth', 'Wamba', 'Roderic'],
      weight: 0.3,
    ),
    'merovingian': CoinPeriodInfo(
      period: 'Merovingian',
      dateRange: '481-751 CE',
      characteristics: ['Tremissis', 'Deniers', 'Crude style', 'Many mints', 'Cross motifs', 'Moneyer names'],
      regions: ['Frankish Gaul', 'Burgundy', 'Austrasia', 'Neustria'],
      materials: ['Gold', 'Silver'],
      denominations: ['Tremissis', 'Solidus', 'Denier'],
      rulers: ['Clovis I', 'Chilperic I', 'Clothar II', 'Dagobert I', 'Childeric III'],
      weight: 0.3,
    ),

    // MEDIEVAL EUROPE
    'carolingian': CoinPeriodInfo(
      period: 'Carolingian Empire',
      dateRange: '751-987 CE',
      characteristics: ['Denier silver', 'Charlemagne', 'Monogram', 'Temple design', 'Cross potent', 'CARLVS'],
      regions: ['Frankish Empire', 'Italy', 'Germany', 'Lotharingia'],
      materials: ['Silver'],
      denominations: ['Denier', 'Obol'],
      rulers: ['Pepin III', 'Charlemagne', 'Louis the Pious', 'Charles the Bald', 'Louis II'],
      weight: 0.35,
    ),
    'viking': CoinPeriodInfo(
      period: 'Viking Age',
      dateRange: '793-1066 CE',
      characteristics: ['Imitations', 'Hack silver', 'Thor hammer', 'Raven', 'Ship', 'Penny'],
      regions: ['Scandinavia', 'England', 'Ireland', 'Normandy', 'York'],
      materials: ['Silver'],
      denominations: ['Penny', 'Halfpenny', 'Sceatta'],
      rulers: ['Cnut', 'Olaf Tryggvason', 'Harald Bluetooth', 'Sven Forkbeard', 'Eric Bloodaxe'],
      weight: 0.3,
    ),
    'anglo_saxon': CoinPeriodInfo(
      period: 'Anglo-Saxon',
      dateRange: '600-1066 CE',
      characteristics: ['Sceatta', 'Penny', 'Portrait busts', 'Cross patterns', 'PACX'],
      regions: ['England', 'Kent', 'Mercia', 'Northumbria', 'Wessex'],
      materials: ['Silver', 'Gold'],
      denominations: ['Penny', 'Shilling', 'Thrymsa', 'Sceatta', 'Styca'],
      rulers: ['Offa', 'Alfred the Great', 'Athelstan', 'Edgar', 'Aethelred II', 'Edward the Confessor'],
      weight: 0.35,
    ),
    'high_medieval': CoinPeriodInfo(
      period: 'High Medieval',
      dateRange: '1000-1300 CE',
      characteristics: ['Long cross', 'Short cross', 'Crusader types', 'Grosso', 'Bracteate', 'Gros tournois'],
      regions: ['England', 'France', 'Holy Roman Empire', 'Italian states', 'Crusader States'],
      materials: ['Silver', 'Gold', 'Billon'],
      denominations: ['Penny', 'Groat', 'Grosso', 'Gros', 'Denier', 'Sterling', 'Pfennig', 'Bracteate'],
      rulers: ['William I', 'Henry II', 'Richard I', 'Philip II', 'Frederick II', 'Louis IX'],
      weight: 0.35,
    ),
    'crusader': CoinPeriodInfo(
      period: 'Crusader States',
      dateRange: '1099-1291 CE',
      characteristics: ['Cross designs', 'Latin legends', 'Arabic imitations', 'Bezant', 'Church of Holy Sepulchre'],
      regions: ['Jerusalem', 'Antioch', 'Tripoli', 'Acre', 'Edessa', 'Cyprus'],
      materials: ['Gold', 'Silver', 'Billon'],
      denominations: ['Bezant', 'Denier', 'Obole', 'Dirham imitations'],
      rulers: ['Baldwin I-V', 'Amalric', 'Guy de Lusignan', 'Bohemond', 'Raymond'],
      weight: 0.35,
    ),
    'late_medieval': CoinPeriodInfo(
      period: 'Late Medieval',
      dateRange: '1300-1500 CE',
      characteristics: ['Florins', 'Ducats', 'Groats', 'Detailed heraldry', 'Renaissance influence', 'Noble'],
      regions: ['Florence', 'Venice', 'England', 'France', 'Burgundy', 'Castile'],
      materials: ['Gold', 'Silver'],
      denominations: ['Florin', 'Ducat', 'Noble', 'Groat', 'Écu', 'Franc', 'Real'],
      rulers: ['Edward III', 'Charles V', 'Philip the Good', 'Ferdinand & Isabella'],
      weight: 0.35,
    ),

    // ISLAMIC WORLD
    'umayyad': CoinPeriodInfo(
      period: 'Umayyad Caliphate',
      dateRange: '661-750 CE',
      characteristics: ['Arabic script only', 'No images', 'Kalima', 'Mint names', 'Hijri dates'],
      regions: ['Damascus', 'North Africa', 'Spain (Al-Andalus)', 'Persia'],
      materials: ['Gold', 'Silver', 'Bronze'],
      denominations: ['Dinar', 'Dirham', 'Fals'],
      rulers: ['Abd al-Malik', 'Al-Walid I', 'Umar II', 'Hisham', 'Marwan II'],
      weight: 0.4,
    ),
    'abbasid': CoinPeriodInfo(
      period: 'Abbasid Caliphate',
      dateRange: '750-1258 CE',
      characteristics: ['Kufic script', 'Caliphal names', 'Mint names', 'Double margin', 'Religious inscriptions'],
      regions: ['Baghdad', 'Persia', 'Central Asia', 'Egypt'],
      materials: ['Gold', 'Silver', 'Bronze'],
      denominations: ['Dinar', 'Dirham', 'Fals', 'Fractional Dirham'],
      rulers: ['Al-Mansur', 'Harun al-Rashid', 'Al-Mamun', 'Al-Mutawakkil'],
      weight: 0.4,
    ),
    'fatimid': CoinPeriodInfo(
      period: 'Fatimid Caliphate',
      dateRange: '909-1171 CE',
      characteristics: ['Concentric circles', 'Shia legends', 'Egypt-centered', 'High gold content'],
      regions: ['Egypt', 'North Africa', 'Sicily', 'Syria', 'Hejaz'],
      materials: ['Gold', 'Silver'],
      denominations: ['Dinar', 'Quarter Dinar', 'Dirham', 'Half Dirham'],
      rulers: ['Al-Mahdi', 'Al-Muizz', 'Al-Hakim', 'Al-Mustansir'],
      weight: 0.35,
    ),
    'ayyubid': CoinPeriodInfo(
      period: 'Ayyubid Dynasty',
      dateRange: '1171-1260 CE',
      characteristics: ['Saladin', 'Crusader conflict', 'Egyptian style', 'Citadel imagery'],
      regions: ['Egypt', 'Syria', 'Yemen', 'Mesopotamia'],
      materials: ['Gold', 'Silver', 'Bronze'],
      denominations: ['Dinar', 'Dirham', 'Fals'],
      rulers: ['Saladin', 'Al-Adil I', 'Al-Kamil', 'As-Salih Ayyub'],
      weight: 0.35,
    ),
    'mamluk': CoinPeriodInfo(
      period: 'Mamluk Sultanate',
      dateRange: '1250-1517 CE',
      characteristics: ['Sultanate titles', 'Heraldic blazons', 'Large flans', 'Lion emblems'],
      regions: ['Egypt', 'Syria', 'Hejaz'],
      materials: ['Gold', 'Silver', 'Bronze'],
      denominations: ['Ashrafi', 'Dirham', 'Fals', 'Nasiri'],
      rulers: ['Baybars', 'Qalawun', 'Al-Nasir Muhammad', 'Barquq', 'Qa\'itbay'],
      weight: 0.35,
    ),
    'ottoman': CoinPeriodInfo(
      period: 'Ottoman Empire',
      dateRange: '1299-1924 CE',
      characteristics: ['Tughra', 'Sultan\'s name', 'Mint marks', 'Accession year'],
      regions: ['Turkey', 'Balkans', 'Middle East', 'North Africa', 'Egypt'],
      materials: ['Gold', 'Silver', 'Bronze', 'Billon'],
      denominations: ['Sultani', 'Akçe', 'Para', 'Kuruş', 'Mangır', 'Zeri Mahbub'],
      rulers: ['Mehmed II', 'Suleiman I', 'Murad IV', 'Ahmed III', 'Mahmud II', 'Abdulhamid II'],
      weight: 0.4,
    ),

    // PERSIAN & CENTRAL ASIAN
    'achaemenid': CoinPeriodInfo(
      period: 'Persian Empire (Achaemenid)',
      dateRange: '550-330 BCE',
      characteristics: ['Daric', 'Siglos', 'Archer king', 'Incuse reverse', 'Thick flan', 'Running king'],
      regions: ['Persia', 'Asia Minor', 'Babylon', 'Egypt'],
      materials: ['Gold', 'Silver'],
      denominations: ['Daric', 'Siglos', 'Double Daric'],
      rulers: ['Cyrus II', 'Darius I', 'Xerxes I', 'Artaxerxes I-III', 'Darius III'],
      weight: 0.4,
    ),
    'parthian': CoinPeriodInfo(
      period: 'Parthian Empire',
      dateRange: '247 BCE - 224 CE',
      characteristics: ['Archer reverse', 'Drachm', 'Royal portraits', 'Greek legends', 'Tiara', 'Bearded king'],
      regions: ['Persia', 'Mesopotamia', 'Bactria', 'Armenia'],
      materials: ['Silver', 'Bronze'],
      denominations: ['Tetradrachm', 'Drachm', 'Dichalkon', 'Chalkos'],
      rulers: ['Mithridates I-II', 'Orodes II', 'Phraates IV', 'Vologases I-VI'],
      weight: 0.4,
    ),
    'sasanian': CoinPeriodInfo(
      period: 'Sasanian Empire',
      dateRange: '224-651 CE',
      characteristics: ['Fire altar', 'Drachm', 'Distinctive crowns', 'Thin flan', 'Pahlavi script', 'Attendants'],
      regions: ['Persia', 'Mesopotamia', 'Central Asia', 'Afghanistan'],
      materials: ['Silver', 'Gold', 'Bronze'],
      denominations: ['Drachm', 'Hemidrachm', 'Obol', 'Dinar'],
      rulers: ['Ardashir I', 'Shapur I-II', 'Bahram V', 'Khosrow I-II', 'Yazdegerd III'],
      weight: 0.45,
    ),

    // JEWISH COINAGE
    'hasmonean': CoinPeriodInfo(
      period: 'Hasmonean Dynasty',
      dateRange: '140-37 BCE',
      characteristics: ['Hebrew script', 'No portraits', 'Cornucopia', 'Anchor', 'Star', 'Wreath'],
      regions: ['Judea', 'Jerusalem'],
      materials: ['Bronze'],
      denominations: ['Prutah', 'Half Prutah', 'Lepton'],
      rulers: ['John Hyrcanus I', 'Alexander Jannaeus', 'Salome Alexandra', 'Hyrcanus II', 'Antigonus'],
      weight: 0.35,
    ),
    'herodian': CoinPeriodInfo(
      period: 'Herodian Dynasty',
      dateRange: '37 BCE - 92 CE',
      characteristics: ['Greek legends', 'No portraits (mostly)', 'Symbolic designs', 'Galley', 'Palm branch'],
      regions: ['Judea', 'Galilee', 'Samaria'],
      materials: ['Bronze'],
      denominations: ['Prutah', 'Half Prutah', 'Lepton', '8 Prutot'],
      rulers: ['Herod the Great', 'Herod Archelaus', 'Herod Antipas', 'Agrippa I-II'],
      weight: 0.35,
    ),
    'jewish_revolt': CoinPeriodInfo(
      period: 'Jewish Revolt',
      dateRange: '66-135 CE',
      characteristics: ['Hebrew/Paleo-Hebrew', 'Temple imagery', 'Year dates', 'Vine leaf', 'Chalice', 'Lyre'],
      regions: ['Judea', 'Jerusalem'],
      materials: ['Silver', 'Bronze'],
      denominations: ['Shekel', 'Half Shekel', 'Quarter Shekel', 'Prutah'],
      rulers: ['First Jewish Revolt', 'Bar Kokhba'],
      weight: 0.4,
    ),

    // INDIAN SUBCONTINENT
    'mauryan': CoinPeriodInfo(
      period: 'Mauryan Empire',
      dateRange: '322-185 BCE',
      characteristics: ['Punch-marked', 'Multiple symbols', 'Bent bar', 'Sun symbol', 'Elephant', 'Tree'],
      regions: ['India', 'Afghanistan', 'Bangladesh', 'Pakistan'],
      materials: ['Silver', 'Copper'],
      denominations: ['Karshapana', 'Pana', 'Mashaka', 'Kakani'],
      rulers: ['Chandragupta', 'Bindusara', 'Ashoka'],
      weight: 0.35,
    ),
    'indo_greek': CoinPeriodInfo(
      period: 'Indo-Greek Kingdom',
      dateRange: '180 BCE - 10 CE',
      characteristics: ['Bilingual legends', 'Greek/Kharosthi', 'Royal portraits', 'Athena', 'Zeus', 'Tyche'],
      regions: ['Bactria', 'Gandhara', 'Punjab', 'Afghanistan'],
      materials: ['Silver', 'Bronze'],
      denominations: ['Tetradrachm', 'Drachm', 'Hemidrachm', 'Obol', 'Dichalkon'],
      rulers: ['Demetrius I', 'Menander I', 'Eucratides I', 'Apollodotus I'],
      weight: 0.35,
    ),
    'kushan': CoinPeriodInfo(
      period: 'Kushan Empire',
      dateRange: '30-375 CE',
      characteristics: ['Standing king', 'Deities', 'Greek legends', 'Buddhist symbols', 'Shiva', 'Buddha'],
      regions: ['Central Asia', 'Northern India', 'Afghanistan', 'Pakistan'],
      materials: ['Gold', 'Copper'],
      denominations: ['Dinar', 'Quarter Dinar', 'Tetradrachm', 'Drachm'],
      rulers: ['Kujula Kadphises', 'Vima Kadphises', 'Kanishka I', 'Huvishka', 'Vasudeva I'],
      weight: 0.35,
    ),
    'gupta': CoinPeriodInfo(
      period: 'Gupta Empire',
      dateRange: '320-550 CE',
      characteristics: ['Archer king', 'Tiger slayer', 'Lakshmi', 'Sanskrit legends', 'Horseman', 'Lyrist'],
      regions: ['Northern India', 'Bengal', 'Central India'],
      materials: ['Gold', 'Silver'],
      denominations: ['Dinar', 'Rupaka', 'Karshapana'],
      rulers: ['Chandragupta I', 'Samudragupta', 'Chandragupta II', 'Kumaragupta I', 'Skandagupta'],
      weight: 0.35,
    ),
    'mughal': CoinPeriodInfo(
      period: 'Mughal Empire',
      dateRange: '1526-1857 CE',
      characteristics: ['Persian script', 'Zodiac types', 'Couplets', 'Kalima', 'Mint marks'],
      regions: ['India', 'Pakistan', 'Bangladesh', 'Afghanistan'],
      materials: ['Gold', 'Silver', 'Copper'],
      denominations: ['Mohur', 'Rupee', 'Dam', 'Paisa', 'Half Rupee', 'Quarter Rupee'],
      rulers: ['Babur', 'Humayun', 'Akbar', 'Jahangir', 'Shah Jahan', 'Aurangzeb'],
      weight: 0.4,
    ),

    // CHINESE & EAST ASIAN
    'chinese_ancient': CoinPeriodInfo(
      period: 'Ancient Chinese',
      dateRange: '770 BCE - 221 BCE',
      characteristics: ['Spade money', 'Knife money', 'Cowrie', 'Cast bronze', 'Ant-nose'],
      regions: ['China', 'Zhou Dynasty states', 'Warring States'],
      materials: ['Bronze'],
      denominations: ['Bu (Spade)', 'Dao (Knife)', 'Yuan (Round)', 'Yi Hua'],
      rulers: ['Various Zhou states', 'Qin', 'Chu', 'Qi', 'Yan'],
      weight: 0.3,
    ),
    'chinese_imperial': CoinPeriodInfo(
      period: 'Chinese Imperial',
      dateRange: '221 BCE - 1912 CE',
      characteristics: ['Round with square hole', 'Cash coins', 'Cast bronze', 'Reign marks', 'Calligraphy'],
      regions: ['China', 'Vietnam', 'Korea', 'Japan'],
      materials: ['Bronze', 'Iron', 'Brass'],
      denominations: ['Cash (Wen)', 'Multiple Cash', 'Tael', 'Sycee'],
      rulers: ['Qin Shi Huang', 'Han Wudi', 'Tang Taizong', 'Song Taizu', 'Kangxi', 'Qianlong'],
      weight: 0.4,
    ),

    // ═══════════════════════════════════════════════════════════════════════════
    // MODERN COINS (1900 - Present)
    // ═══════════════════════════════════════════════════════════════════════════

    // UNITED STATES
    'us_modern': CoinPeriodInfo(
      period: 'United States (Modern)',
      dateRange: '1965 - Present',
      characteristics: ['Clad coinage', 'Copper-nickel', 'In God We Trust', 'E Pluribus Unum', 'Liberty', 'Eagle', 'Presidential portraits', 'State quarters', 'America the Beautiful'],
      regions: ['United States', 'US Mint Philadelphia', 'Denver', 'San Francisco', 'West Point'],
      materials: ['Copper-Nickel Clad', 'Copper Plated Zinc', 'Manganese-Brass', 'Silver Proof'],
      denominations: ['Cent (Penny)', 'Nickel (5c)', 'Dime (10c)', 'Quarter (25c)', 'Half Dollar (50c)', 'Dollar', 'Presidential Dollar', 'Sacagawea Dollar'],
      rulers: ['Lincoln (Cent)', 'Jefferson (Nickel)', 'Roosevelt (Dime)', 'Washington (Quarter)', 'Kennedy (Half)', 'Eisenhower', 'Susan B. Anthony', 'Sacagawea'],
      weight: 0.5,
    ),
    'us_classic': CoinPeriodInfo(
      period: 'United States (Classic)',
      dateRange: '1900 - 1964',
      characteristics: ['Silver coinage', '90% silver', 'Walking Liberty', 'Mercury dime', 'Buffalo nickel', 'Indian head', 'Morgan', 'Peace dollar', 'Franklin half'],
      regions: ['United States', 'Philadelphia', 'Denver', 'San Francisco', 'New Orleans', 'Carson City'],
      materials: ['90% Silver', 'Bronze', 'Copper', 'Nickel'],
      denominations: ['Cent', 'Nickel', 'Dime', 'Quarter', 'Half Dollar', 'Dollar', 'Gold Eagle'],
      rulers: ['Lincoln', 'Indian Head', 'Buffalo', 'Mercury', 'Walking Liberty', 'Franklin', 'Morgan', 'Peace'],
      weight: 0.5,
    ),

    // EUROZONE (HIGH PRIORITY - very common modern coin)
    'euro': CoinPeriodInfo(
      period: 'Eurozone (Euro)',
      dateRange: '1999 - Present',
      characteristics: [
        'Euro', 'EURO', 'cent', 'Cent', 'EUR', 'European',
        'Nordic Gold', 'Gold colored', 'Copper colored', 'Yellow brass',
        '12 stars', 'Stars of Europe', 'Circle of stars', 'Star ring',
        'Map of Europe', 'EU map', 'Europa',
        'Bi-metallic 1 Euro', 'Bi-metallic 2 Euro',
        'Sowing figure', 'Woman sowing seeds', '50 cent design',
        'National side', 'Common side', 'Country-specific',
        'Marianne', 'Brandenburg Gate', 'Dante', 'Harp', 'Oak leaf',
        'Smooth edge', 'Reeded edge', 'Spanish flower edge',
      ],
      regions: ['European Union', 'EU', 'Europe', 'Germany', 'France', 'Italy', 'Spain', 'Netherlands', 'Belgium', 'Austria', 'Greece', 'Ireland', 'Portugal', 'Finland', 'Luxembourg', 'Slovenia', 'Cyprus', 'Malta', 'Slovakia', 'Estonia', 'Latvia', 'Lithuania'],
      materials: ['Nordic Gold', 'Copper-Nickel', 'Copper plated steel', 'Bi-metallic'],
      denominations: ['1 Cent', '2 Cent', '5 Cent', '10 Cent', '20 Cent', '50 Cent', '1 Euro', '2 Euro', 'Euro cent', 'Eurocent'],
      rulers: ['National symbols', 'Marianne (France)', 'Brandenburg Gate (Germany)', 'Dante (Italy)', 'King Felipe VI (Spain)', 'King Philippe (Belgium)', 'Harp (Ireland)', 'Mozart (Austria)', 'Oak twig (Germany)'],
      weight: 0.5,  // Balanced weight - same as other modern coins
    ),

    // UNITED KINGDOM
    'uk_modern': CoinPeriodInfo(
      period: 'United Kingdom (Modern)',
      dateRange: '1971 - Present',
      characteristics: ['Decimal coinage', 'Royal portrait', 'Britannia', 'Royal Shield', 'Queen Elizabeth II', 'King Charles III', 'New Pence', 'Royal Mint'],
      regions: ['United Kingdom', 'England', 'Scotland', 'Wales', 'Northern Ireland', 'Royal Mint Llantrisant'],
      materials: ['Copper Plated Steel', 'Nickel-Brass', 'Cupro-Nickel', 'Bi-metallic'],
      denominations: ['1 Penny', '2 Pence', '5 Pence', '10 Pence', '20 Pence', '50 Pence', '1 Pound', '2 Pounds'],
      rulers: ['Elizabeth II', 'Charles III', 'Britannia', 'Royal Arms', 'Thistle', 'Leek', 'Shamrock', 'Rose'],
      weight: 0.5,
    ),
    'uk_pre_decimal': CoinPeriodInfo(
      period: 'United Kingdom (Pre-Decimal)',
      dateRange: '1900 - 1971',
      characteristics: ['Pounds Shillings Pence', 'LSD system', 'Farthing', 'Crown', 'Florin', 'Guinea tradition', 'Victorian', 'Edwardian', 'Georgian'],
      regions: ['United Kingdom', 'British Empire', 'Commonwealth'],
      materials: ['Silver', 'Bronze', 'Cupro-Nickel', 'Brass'],
      denominations: ['Farthing', 'Halfpenny', 'Penny', 'Threepence', 'Sixpence', 'Shilling', 'Florin', 'Half Crown', 'Crown'],
      rulers: ['Victoria', 'Edward VII', 'George V', 'Edward VIII', 'George VI', 'Elizabeth II'],
      weight: 0.45,
    ),

    // CANADA
    'canada_modern': CoinPeriodInfo(
      period: 'Canada (Modern)',
      dateRange: '1968 - Present',
      characteristics: ['Maple leaf', 'Beaver', 'Caribou', 'Bluenose schooner', 'Loon dollar', 'Toonie', 'Royal Canadian Mint', 'Bilingual'],
      regions: ['Canada', 'Royal Canadian Mint Ottawa', 'Winnipeg'],
      materials: ['Nickel', 'Copper Plated Steel', 'Multi-ply Brass', 'Bi-metallic'],
      denominations: ['1 Cent (Discontinued)', '5 Cents', '10 Cents', '25 Cents', '50 Cents', '1 Dollar (Loonie)', '2 Dollars (Toonie)'],
      rulers: ['Elizabeth II', 'Charles III', 'Maple Leaf', 'Beaver', 'Caribou', 'Loon', 'Polar Bear'],
      weight: 0.45,
    ),

    // AUSTRALIA
    'australia_modern': CoinPeriodInfo(
      period: 'Australia (Modern)',
      dateRange: '1966 - Present',
      characteristics: ['Decimal currency', 'Kangaroo', 'Platypus', 'Echidna', 'Lyrebird', 'Aboriginal art', 'Royal Australian Mint', 'Perth Mint'],
      regions: ['Australia', 'Royal Australian Mint Canberra', 'Perth Mint'],
      materials: ['Copper Plated Steel', 'Cupro-Nickel', 'Aluminium Bronze', 'Bi-metallic'],
      denominations: ['5 Cents', '10 Cents', '20 Cents', '50 Cents', '1 Dollar', '2 Dollars'],
      rulers: ['Elizabeth II', 'Charles III', 'Kangaroo', 'Platypus', 'Echidna', 'Lyrebird', 'Aboriginal Elder'],
      weight: 0.45,
    ),

    // JAPAN
    'japan_modern': CoinPeriodInfo(
      period: 'Japan (Modern)',
      dateRange: '1948 - Present',
      characteristics: ['Yen', 'Cherry blossom', 'Chrysanthemum', 'Paulownia', 'Emperor era dating', 'Showa', 'Heisei', 'Reiwa', 'Hole in 5 and 50 yen'],
      regions: ['Japan', 'Japan Mint Osaka', 'Hiroshima'],
      materials: ['Aluminium', 'Brass', 'Cupro-Nickel', 'Nickel-Brass'],
      denominations: ['1 Yen', '5 Yen', '10 Yen', '50 Yen', '100 Yen', '500 Yen'],
      rulers: ['Hirohito (Showa)', 'Akihito (Heisei)', 'Naruhito (Reiwa)', 'Chrysanthemum Crest'],
      weight: 0.45,
    ),

    // CHINA (MODERN)
    'china_modern': CoinPeriodInfo(
      period: 'China (Modern PRC)',
      dateRange: '1955 - Present',
      characteristics: ['Renminbi', 'Yuan', 'Jiao', 'National emblem', 'Tiananmen Gate', 'Flower series', 'Simplified Chinese'],
      regions: ['China', 'People\'s Republic of China', 'Shanghai Mint', 'Shenyang Mint'],
      materials: ['Aluminium', 'Steel', 'Nickel Plated Steel', 'Brass', 'Bi-metallic'],
      denominations: ['1 Fen', '2 Fen', '5 Fen', '1 Jiao', '5 Jiao', '1 Yuan'],
      rulers: ['National Emblem', 'Orchid', 'Lotus', 'Chrysanthemum', 'Plum Blossom'],
      weight: 0.45,
    ),

    // INDIA (MODERN)
    'india_modern': CoinPeriodInfo(
      period: 'India (Modern Republic)',
      dateRange: '1950 - Present',
      characteristics: ['Indian Rupee', 'Ashoka Lion Capital', 'Rupee symbol', 'Mahatma Gandhi', 'Red Fort', 'India Map', 'Hindi and English'],
      regions: ['India', 'India Government Mint Mumbai', 'Kolkata', 'Hyderabad', 'Noida'],
      materials: ['Stainless Steel', 'Cupro-Nickel', 'Ferritic Stainless Steel', 'Bi-metallic'],
      denominations: ['1 Paisa (Discontinued)', '5 Paise', '10 Paise', '25 Paise', '50 Paise', '1 Rupee', '2 Rupees', '5 Rupees', '10 Rupees'],
      rulers: ['Ashoka Pillar', 'Lion Capital', 'Mahatma Gandhi', 'National Emblem'],
      weight: 0.45,
    ),

    // MEXICO
    'mexico_modern': CoinPeriodInfo(
      period: 'Mexico (Modern)',
      dateRange: '1993 - Present',
      characteristics: ['Nuevo Peso', 'PESOS', 'Peso', 'Centavos', 'Eagle and serpent', 'Golden eagle', 'Aztec calendar', 'Aztec sunstone', 'Angel of Independence', 'Estados Unidos Mexicanos', 'Mexico', 'Mexican eagle'],
      regions: ['Mexico', 'Casa de Moneda de México', 'Mexican Mint'],
      materials: ['Stainless Steel', 'Bronze', 'Bi-metallic (Bronze/Stainless)', 'Silver (Commemorative)'],
      denominations: ['5 Centavos', '10 Centavos', '20 Centavos', '50 Centavos', '1 Peso', '2 Pesos', '5 Pesos', '10 Pesos', '20 Pesos', '50 Pesos', '100 Pesos'],
      rulers: ['Eagle with Serpent', 'Aztec Sunstone', 'Miguel Hidalgo', 'Benito Juárez', 'José María Morelos', 'Cuauhtémoc'],
      weight: 0.45,  // Balanced weight
    ),

    // RUSSIA
    'russia_modern': CoinPeriodInfo(
      period: 'Russia (Modern Federation)',
      dateRange: '1992 - Present',
      characteristics: ['Russian Ruble', 'Double-headed eagle', 'St. George', 'Cyrillic script', 'Bank of Russia', 'Bi-metallic'],
      regions: ['Russia', 'Moscow Mint', 'Saint Petersburg Mint'],
      materials: ['Steel', 'Brass Plated Steel', 'Cupro-Nickel', 'Bi-metallic'],
      denominations: ['1 Kopek', '5 Kopeks', '10 Kopeks', '50 Kopeks', '1 Ruble', '2 Rubles', '5 Rubles', '10 Rubles'],
      rulers: ['Double-Headed Eagle', 'St. George Slaying Dragon', 'Bank of Russia Emblem'],
      weight: 0.45,
    ),

    // SWITZERLAND
    'swiss_modern': CoinPeriodInfo(
      period: 'Switzerland (Modern)',
      dateRange: '1968 - Present',
      characteristics: ['Swiss Franc', 'Helvetia', 'Swiss cross', 'Libertas', 'William Tell', 'High quality', 'Multilingual'],
      regions: ['Switzerland', 'Swiss Mint Bern'],
      materials: ['Cupro-Nickel', 'Aluminium-Bronze', 'Bi-metallic'],
      denominations: ['5 Rappen', '10 Rappen', '20 Rappen', '½ Franc', '1 Franc', '2 Francs', '5 Francs'],
      rulers: ['Helvetia', 'Libertas', 'Swiss Cross', 'William Tell'],
      weight: 0.45,
    ),

    // SOUTH KOREA
    'korea_modern': CoinPeriodInfo(
      period: 'South Korea (Modern)',
      dateRange: '1966 - Present',
      characteristics: ['Korean Won', 'Rose of Sharon', 'Turtle ship', 'Dabotap Pagoda', 'Admiral Yi Sun-sin', 'Hangul script'],
      regions: ['South Korea', 'Korea Minting and Security Printing Corporation'],
      materials: ['Aluminium', 'Brass', 'Cupro-Nickel', 'Copper-Nickel-Zinc'],
      denominations: ['1 Won', '5 Won', '10 Won', '50 Won', '100 Won', '500 Won'],
      rulers: ['Yi Sun-sin', 'Rose of Sharon', 'Turtle Ship', 'Dabotap Pagoda', 'Crane'],
      weight: 0.45,
    ),

    // BRAZIL
    'brazil_modern': CoinPeriodInfo(
      period: 'Brazil (Modern Real)',
      dateRange: '1994 - Present',
      characteristics: ['Brazilian Real', 'Southern Cross', 'Effigy of Republic', 'Bi-metallic', 'Central Bank of Brazil'],
      regions: ['Brazil', 'Casa da Moeda do Brasil Rio de Janeiro'],
      materials: ['Copper Plated Steel', 'Bronze Plated Steel', 'Stainless Steel', 'Bi-metallic'],
      denominations: ['1 Centavo', '5 Centavos', '10 Centavos', '25 Centavos', '50 Centavos', '1 Real'],
      rulers: ['Effigy of Republic', 'Southern Cross', 'Pedro Álvares Cabral', 'Tiradentes', 'Juscelino Kubitschek'],
      weight: 0.45,
    ),

    // SOUTH AFRICA
    'south_africa_modern': CoinPeriodInfo(
      period: 'South Africa (Modern)',
      dateRange: '1961 - Present',
      characteristics: ['South African Rand', 'Springbok', 'Big Five animals', 'Coat of Arms', 'Krugerrand', 'Multilingual', '11 languages'],
      regions: ['South Africa', 'South African Mint Pretoria'],
      materials: ['Copper Plated Steel', 'Bronze Plated Steel', 'Nickel Plated Copper', 'Bi-metallic'],
      denominations: ['5 Cents', '10 Cents', '20 Cents', '50 Cents', '1 Rand', '2 Rand', '5 Rand'],
      rulers: ['Springbok', 'Wildebeest', 'Kudu', 'Bird', 'Coat of Arms', 'Nelson Mandela'],
      weight: 0.45,
    ),

    // TURKEY
    'turkey_modern': CoinPeriodInfo(
      period: 'Turkey (Modern Lira)',
      dateRange: '2005 - Present',
      characteristics: ['Turkish Lira', 'Atatürk portrait', 'Crescent and star', 'Turkish Republic', 'Bi-metallic'],
      regions: ['Turkey', 'Turkish State Mint Istanbul'],
      materials: ['Brass', 'Cupro-Nickel', 'Bi-metallic'],
      denominations: ['1 Kuruş', '5 Kuruş', '10 Kuruş', '25 Kuruş', '50 Kuruş', '1 Lira'],
      rulers: ['Mustafa Kemal Atatürk', 'Crescent and Star', 'Republic Emblem'],
      weight: 0.45,
    ),
  };
}
