#!/usr/bin/env python3
"""
generate_full_report.py — Generate a comprehensive field report by running all analysis scripts.

Usage:
    python scripts/generate_full_report.py [--data-dir DIR] [--output FILE] [--open]

Runs all analysis scripts in sequence, captures their stdout, and combines them into
a single Markdown file. Useful for end-of-day field reporting.

--data-dir: directory containing field CSVs (default: ./data/field)
--output:   report filename (default: field_report_YYYY-MM-DD.md)
--open:     open the report in the default browser after generation
"""

import argparse
import subprocess
import sys
import time
from datetime import date
from pathlib import Path

SCRIPTS_DIR = Path(__file__).parent

# Ordered list of (script_filename, description) pairs to include.
# Only scripts whose file actually exists in SCRIPTS_DIR will be run.
REPORT_SCRIPTS = [
    ("field_report.py",        "Field Summary"),
    ("session_risk_report.py", "Session Risk Table"),
    ("ppv_trend_analysis.py",  "PPV Trend Analysis"),
    ("alert_correlation.py",   "Alert Correlation"),
    ("sensor_noise_floor.py",  "Sensor Noise Floor"),
    ("retrain_advisor.py",     "Retraining Recommendation"),
    ("data_drift_detector.py", "Data Drift Check"),
    ("training_history.py",    "ML Training History"),
    ("model_size_report.py",   "Model Sizes"),
    ("site_summary_report.py", "Site Summary"),
]

TIMEOUT_SECONDS = 30


def _run_script(script_path: Path, data_dir: str) -> tuple[str, float, bool]:
    """
    Run a single script as a subprocess, capturing stdout+stderr.

    Returns (output_text, elapsed_seconds, success).
    success is False if the process exits non-zero or times out.
    """
    cmd = [sys.executable, str(script_path), "--data-dir", data_dir]
    t0 = time.monotonic()
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=TIMEOUT_SECONDS,
        )
        elapsed = time.monotonic() - t0
        combined = result.stdout
        if result.returncode != 0:
            # Include stderr in the error output so the report is informative.
            stderr_snippet = result.stderr.strip()
            if stderr_snippet:
                combined = (
                    f"[exit code {result.returncode}]\n\n"
                    f"stderr:\n{stderr_snippet}\n\n"
                    f"stdout:\n{result.stdout}"
                )
            else:
                combined = f"[exit code {result.returncode}]\n\n{result.stdout}"
            return combined, elapsed, False
        return combined, elapsed, True
    except subprocess.TimeoutExpired:
        elapsed = time.monotonic() - t0
        return f"[TIMEOUT after {TIMEOUT_SECONDS}s]", elapsed, False
    except Exception as exc:  # pragma: no cover
        elapsed = time.monotonic() - t0
        return f"[ERROR launching script: {exc}]", elapsed, False


def _section_markdown(title: str, output: str, elapsed: float, success: bool) -> str:
    """Return the Markdown block for one script section."""
    lines = []
    lines.append(f"## {title}")
    lines.append("")
    if success:
        lines.append("```")
        lines.append(output.rstrip())
        lines.append("```")
        lines.append("")
        lines.append(f"_Section completed in {elapsed:.1f}s_")
    else:
        lines.append("> **ERROR / NON-ZERO EXIT**")
        lines.append(">")
        for err_line in output.rstrip().splitlines():
            lines.append(f"> {err_line}")
        lines.append("")
        lines.append(f"_Section failed after {elapsed:.1f}s_")
    lines.append("")
    return "\n".join(lines)


def generate_report(data_dir: str, output_path: Path) -> int:
    """
    Run all analysis scripts, assemble the Markdown report, and write it.

    Returns the number of sections successfully generated.
    """
    total_start = time.monotonic()

    # Determine which scripts actually exist.
    available = [
        (fname, title)
        for fname, title in REPORT_SCRIPTS
        if (SCRIPTS_DIR / fname).exists()
    ]
    total = len(available)

    report_lines = []

    # Report header
    today = date.today().isoformat()
    report_lines.append(f"# AncientVision Field Report — {today}")
    report_lines.append("")
    report_lines.append(
        f"_Generated by `generate_full_report.py` — {total} section(s) from {total} available script(s)_"
    )
    report_lines.append("")
    report_lines.append("---")
    report_lines.append("")

    success_count = 0
    for idx, (fname, title) in enumerate(available, start=1):
        script_path = SCRIPTS_DIR / fname
        print(f"Running {idx}/{total}: {fname}...", file=sys.stderr)

        output, elapsed, ok = _run_script(script_path, data_dir)
        if ok:
            success_count += 1

        section_md = _section_markdown(title, output, elapsed, ok)
        report_lines.append(section_md)

    total_elapsed = time.monotonic() - total_start

    # Footer summary
    report_lines.append("---")
    report_lines.append("")
    report_lines.append(
        f"_Report complete: {success_count}/{total} sections generated "
        f"in {total_elapsed:.1f}s total_"
    )
    report_lines.append("")

    report_content = "\n".join(report_lines)
    output_path.write_text(report_content, encoding="utf-8")

    print(
        f"\nReport written to: {output_path}  "
        f"({success_count}/{total} sections, {total_elapsed:.1f}s)",
        file=sys.stderr,
    )
    return success_count


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Generate a comprehensive field report combining all analysis outputs."
    )
    parser.add_argument(
        "--data-dir",
        default=str(SCRIPTS_DIR.parent / "data" / "field"),
        help="Directory containing field CSV files (default: ./data/field)",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output Markdown file path (default: field_report_YYYY-MM-DD.md)",
    )
    parser.add_argument(
        "--open",
        action="store_true",
        help="Open the report in the default browser after generation",
    )
    args = parser.parse_args(argv)

    # Resolve output path
    if args.output:
        output_path = Path(args.output)
    else:
        output_path = Path(f"field_report_{date.today().isoformat()}.md")

    generate_report(args.data_dir, output_path)

    if args.open:
        subprocess.run(
            [sys.executable, "-m", "webbrowser", str(output_path)],
            check=False,
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
