"""
Integration-style tests for the AncientVision ML pipeline.

All tests are pure unit/mock — no real Docker, TensorFlow, or network calls.

Classes:
  TestPipelineDataFlow       — data schema / feature consistency end-to-end
  TestPipelineErrorHandling  — error paths in run_pipeline and validate_config
  TestScriptCompatibility    — import smoke-tests, cross-script data compatibility
"""

import csv
import importlib
import io
import json
import sys
import tempfile
import types
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

# ---------------------------------------------------------------------------
# Path setup: make scripts/ importable
# ---------------------------------------------------------------------------

SCRIPTS_DIR = Path(__file__).parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))


# ---------------------------------------------------------------------------
# Constants mirrored from generate_precursor_data.py (without executing it)
# ---------------------------------------------------------------------------

EXPECTED_FEATURE_NAMES = [
    "rms", "ppv", "freq", "crest", "centroid", "kurtosis", "stalta",
    "arias", "cav", "temp", "psdSlope",
    "ppv_trend", "freq_trend", "kurtosis_trend", "stalta_trend",
    "cusum_max", "autoencoder_score",
]
EXPECTED_FEATURE_COUNT = 17

EXPECTED_CLASS_NAMES = ["normal", "soil_creep", "crack_propagation", "imminent_failure"]
EXPECTED_CLASS_COUNT = 4

# ---------------------------------------------------------------------------
# Helper: load run_pipeline cleanly in a tmp_path context
# ---------------------------------------------------------------------------

def _load_pipeline(tmp_path: Path, monkeypatch):
    """Import run_pipeline with DATA_DIR and ASSETS_DIR pointed at tmp_path."""
    monkeypatch.setenv("DATA_DIR", str(tmp_path / "data"))
    sys.modules.pop("run_pipeline", None)
    import run_pipeline as rp
    rp.DATA_DIR = tmp_path / "data"
    rp.TRIGGER_FILE = rp.DATA_DIR / ".retrain_trigger"
    rp.ASSETS_DIR = tmp_path / "assets"
    return rp


# ===========================================================================
# PART 1: TestPipelineDataFlow
# ===========================================================================

class TestPipelineDataFlow:
    """Data schema / feature consistency checks across the pipeline."""

    # -----------------------------------------------------------------------
    def test_generate_to_collect_format(self, tmp_path):
        """
        The collector ingest endpoint expects a JSON payload that includes 'ppv',
        'rms', 'freq', and a 'label' field.  The synthetic data generated by
        generate_precursor_data must produce the same set of numeric features,
        confirming the schemas are compatible without actually running TF training.
        """
        # Define the collector's required ingest fields (from docker/collect/app.py)
        collector_required = {"rms", "ppv", "freq", "crest", "centroid",
                              "kurtosis", "stalta", "arias", "cav", "label"}

        # The generated feature names cover all DSP outputs
        generated_fields = set(EXPECTED_FEATURE_NAMES)

        # Collector fields (excluding label) must be a subset of generated features
        missing = (collector_required - {"label", "temp", "psdSlope"}) - generated_fields
        assert not missing, (
            f"Collector fields not present in generated features: {missing}"
        )

    # -----------------------------------------------------------------------
    def test_feature_count_consistency(self, tmp_path):
        """
        All 17 features must be present in:
          1. EXPECTED_FEATURE_NAMES (mirrors generate_precursor_data.py)
          2. A scaler JSON with the correct number of mean/scale entries
          3. A config JSON with input_dim == 17
        """
        # Build a fake scaler consistent with 17 features
        scaler = {
            "mean": [0.0] * EXPECTED_FEATURE_COUNT,
            "scale": [1.0] * EXPECTED_FEATURE_COUNT,
            "feature_names": EXPECTED_FEATURE_NAMES,
        }
        assert len(scaler["mean"]) == EXPECTED_FEATURE_COUNT
        assert len(scaler["scale"]) == EXPECTED_FEATURE_COUNT
        assert len(scaler["feature_names"]) == EXPECTED_FEATURE_COUNT

        # Build a fake config consistent with 17 features
        config = {
            "input_dim": EXPECTED_FEATURE_COUNT,
            "output_dim": EXPECTED_CLASS_COUNT,
            "feature_names": EXPECTED_FEATURE_NAMES,
            "class_names": EXPECTED_CLASS_NAMES,
        }
        assert config["input_dim"] == EXPECTED_FEATURE_COUNT
        assert len(config["feature_names"]) == EXPECTED_FEATURE_COUNT

    # -----------------------------------------------------------------------
    def test_label_encoding_consistency(self, tmp_path):
        """
        Labels in generated data must map to model class indices consistently:
          normal=0, soil_creep=1, crack_propagation=2, imminent_failure=3.
        """
        label_to_index = {name: i for i, name in enumerate(EXPECTED_CLASS_NAMES)}

        assert label_to_index["normal"] == 0
        assert label_to_index["soil_creep"] == 1
        assert label_to_index["crack_propagation"] == 2
        assert label_to_index["imminent_failure"] == 3

        # Verify the CLASS_NAMES list in the config JSON preserves this ordering
        config = {"class_names": EXPECTED_CLASS_NAMES}
        for idx, name in enumerate(config["class_names"]):
            assert label_to_index[name] == idx, (
                f"Class {name!r} should have index {label_to_index[name]}, "
                f"got {idx} from config class_names list"
            )

    # -----------------------------------------------------------------------
    def test_csv_roundtrip(self, tmp_path):
        """
        Writing a sample dict to CSV and reading it back must preserve all
        field values (within float precision).
        """
        sample = {
            "rms": 0.12345,
            "ppv": 0.34567,
            "freq": 15.0,
            "crest": 3.14,
            "centroid": 25.0,
            "kurtosis": 2.718,
            "stalta": 1.5,
            "arias": 0.001,
            "cav": 0.05,
            "temp": 22.0,
            "psdSlope": -2.0,
            "ppv_trend": 1.05,
            "freq_trend": 0.98,
            "kurtosis_trend": 1.1,
            "stalta_trend": 1.0,
            "cusum_max": 0.3,
            "autoencoder_score": 0.15,
            "label": "normal",
        }

        csv_path = tmp_path / "test_session.csv"
        fieldnames = list(sample.keys())

        # Write
        with open(csv_path, "w", newline="", encoding="utf-8") as fh:
            writer = csv.DictWriter(fh, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerow(sample)

        # Read back
        with open(csv_path, newline="", encoding="utf-8") as fh:
            reader = csv.DictReader(fh)
            rows = list(reader)

        assert len(rows) == 1
        row = rows[0]
        assert row["label"] == "normal"
        for key in EXPECTED_FEATURE_NAMES:
            assert abs(float(row[key]) - sample[key]) < 1e-5, (
                f"CSV roundtrip mismatch for field {key!r}: "
                f"wrote {sample[key]}, read {float(row[key])}"
            )


# ===========================================================================
# PART 2: TestPipelineErrorHandling
# ===========================================================================

class TestPipelineErrorHandling:
    """Error paths in run_pipeline and validate_config."""

    # -----------------------------------------------------------------------
    def test_missing_data_dir_exits_nonzero(self, tmp_path, monkeypatch):
        """
        When no field data directory exists, dry_run() must return 1 (error).
        The pipeline must not proceed to training when data is absent.
        """
        rp = _load_pipeline(tmp_path, monkeypatch)
        rp.DATA_DIR.mkdir(parents=True, exist_ok=True)
        rp.TRIGGER_FILE.touch()
        # field/ deliberately NOT created — simulates a fresh deployment with no data

        result = rp.dry_run()
        assert result == 1, (
            "dry_run() must return 1 when the field data directory is missing"
        )

    # -----------------------------------------------------------------------
    def test_corrupted_model_detected(self, tmp_path):
        """
        validate_config.validate_scaler() must report an error when a scaler JSON
        is syntactically corrupt (truncated / not valid JSON).
        """
        sys.modules.pop("validate_config", None)
        import validate_config as vc

        # Write a corrupt (truncated) JSON file
        corrupt_path = tmp_path / "precursor_classifier_scaler.json"
        corrupt_path.write_text('{"mean": [1.0, 2.0', encoding="utf-8")  # truncated

        data, err = vc._load_json(str(corrupt_path))
        assert data is None, "Corrupt JSON must fail to load"
        assert err is not None, "Error string must be returned for corrupt JSON"
        assert len(err) > 0

    # -----------------------------------------------------------------------
    def test_scaler_dimension_mismatch_detected(self, tmp_path):
        """
        validate_config.validate_scaler() must flag a dimension mismatch between
        'mean' (17 elements) and 'std'/'scale' (wrong number of elements).
        """
        sys.modules.pop("validate_config", None)
        import validate_config as vc

        # Scaler with mismatched mean/std lengths
        scaler_data = {
            "mean": list(range(17)),
            "std": list(range(10)),   # wrong: should be 17
        }

        errors = vc.validate_scaler(scaler_data)
        assert errors, "validate_scaler must report errors for dimension-mismatched scaler"
        combined = " ".join(errors)
        # Should mention lengths
        assert "17" in combined or "10" in combined or "length" in combined.lower(), (
            f"Error message should mention the length mismatch: {errors}"
        )

    # -----------------------------------------------------------------------
    def test_scaler_missing_keys_detected(self, tmp_path):
        """
        validate_config.validate_scaler() must report errors when 'mean' or 'std'
        keys are entirely absent from the scaler JSON.
        """
        sys.modules.pop("validate_config", None)
        import validate_config as vc

        incomplete_scaler = {"feature_names": EXPECTED_FEATURE_NAMES}
        errors = vc.validate_scaler(incomplete_scaler)
        assert errors, "validate_scaler must report errors for missing 'mean'/'std' keys"
        combined = " ".join(errors)
        assert "mean" in combined or "std" in combined, (
            f"Error should mention missing key names: {errors}"
        )


# ===========================================================================
# PART 3: TestScriptCompatibility
# ===========================================================================

class TestScriptCompatibility:
    """Import smoke-tests and cross-script data compatibility checks."""

    # -----------------------------------------------------------------------
    def test_all_scripts_importable(self, tmp_path, monkeypatch):
        """
        A selection of key pipeline scripts must be importable without crashing.
        Scripts that replace sys.stdout at module level are excluded; only
        stdlib-safe scripts are tested here.
        """
        # These scripts use only stdlib or have safe import-time behaviour
        safe_scripts = [
            "compliance_report",
            "validate_config",
            "deployment_readiness",
            "health_check",
            "run_pipeline",
        ]

        monkeypatch.setenv("DATA_DIR", str(tmp_path))

        for script_name in safe_scripts:
            # Do NOT pop from sys.modules — some scripts replace sys.stdout at
            # import time (health_check, pipeline_status) and are already cached
            # by conftest.py. Re-importing under capsys would corrupt stdout.
            try:
                mod = importlib.import_module(script_name)
            except SystemExit:
                # Some scripts call sys.exit() at module scope when run directly;
                # a SystemExit from import is still an import, not a crash.
                pass
            except Exception as exc:
                pytest.fail(
                    f"Script '{script_name}' raised {type(exc).__name__} on import: {exc}"
                )

    # -----------------------------------------------------------------------
    def test_compliance_report_integrates_with_session_data(self, tmp_path):
        """
        compliance_report.load_ppv_from_csv() must correctly parse a session CSV
        that was written in the same format produced by the collect service,
        and compliance check results must reflect the actual PPV values.
        """
        sys.modules.pop("compliance_report", None)
        import compliance_report as cr

        # Write a fake session CSV as the collect service would produce
        csv_path = tmp_path / "session_2026-03-04.csv"
        rows = [
            {"timestamp": "2026-03-04T10:00:00Z", "device_id": "m5-01",
             "ppv": "0.05", "rms": "0.02", "label": "normal"},
            {"timestamp": "2026-03-04T10:00:01Z", "device_id": "m5-01",
             "ppv": "0.15", "rms": "0.06", "label": "normal"},
            {"timestamp": "2026-03-04T10:00:02Z", "device_id": "m5-01",
             "ppv": "0.50", "rms": "0.20", "label": "soil_creep"},
        ]
        with open(csv_path, "w", newline="", encoding="utf-8") as fh:
            writer = csv.DictWriter(fh, fieldnames=rows[0].keys())
            writer.writeheader()
            writer.writerows(rows)

        ppv_values = cr.load_ppv_from_csv(str(csv_path))
        assert len(ppv_values) == 3, (
            f"Expected 3 PPV values, got {len(ppv_values)}"
        )
        assert abs(ppv_values[0] - 0.05) < 1e-9
        assert abs(ppv_values[2] - 0.50) < 1e-9

        # Run a DIN compliance check — 0.50 mm/s exceeds Category I (0.3 mm/s)
        results = cr.run_compliance_checks(ppv_values, ["din"])
        assert len(results) == 1
        din_result = results[0]
        assert din_result["standard_key"] == "din"
        # Category I threshold = 0.3; 0.50 exceeds it → overall_compliant must be False
        assert din_result["overall_compliant"] is False, (
            "PPV of 0.50 mm/s exceeds DIN 4150-3 Category I — should be non-compliant"
        )
        assert din_result["max_ppv"] == pytest.approx(0.50, abs=1e-9)

    # -----------------------------------------------------------------------
    def test_deployment_readiness_matches_actual_files(self, tmp_path, monkeypatch):
        """
        deployment_readiness.run_checks() must correctly detect files that DO exist
        and must not report false positives (FAIL) for those files.

        We patch ROOT to a controlled tmp directory, create the files that the
        check expects, and verify that run_checks() passes for those items.
        """
        sys.modules.pop("deployment_readiness", None)
        import deployment_readiness as dr

        # Build the minimal directory tree that deployment_readiness expects
        fake_root = tmp_path / "repo"
        asset_dir = fake_root / "app" / "assets" / "ml"
        scripts_dir = fake_root / "scripts"
        asset_dir.mkdir(parents=True)
        scripts_dir.mkdir(parents=True)

        # Create the files that fatal checks look for
        files_to_create = [
            asset_dir / "precursor_classifier.tflite",
            asset_dir / "ml_anomaly_model.tflite",
            asset_dir / "precursor_scaler.json",
            scripts_dir / "run_pipeline.py",
            scripts_dir / "health_check.py",
            fake_root / "docker-compose.yml",
            fake_root / "docker-compose.collect.yml",
            fake_root / "docker-compose.train.yml",
        ]
        for p in files_to_create:
            p.write_bytes(b"placeholder content so size > 0")

        # Patch JSON files to be valid JSON
        (asset_dir / "precursor_scaler.json").write_text(
            json.dumps({"mean": [0.0] * 17, "scale": [1.0] * 17}),
            encoding="utf-8",
        )

        # Monkeypatch dr.ROOT and derived dirs so checks point at our fake repo
        monkeypatch.setattr(dr, "ROOT", fake_root)
        monkeypatch.setattr(dr, "ASSET_DIR", asset_dir)
        monkeypatch.setattr(dr, "SCRIPTS_DIR", scripts_dir)
        monkeypatch.setattr(dr, "DATA_DIR", fake_root / "data" / "field")

        # Rebuild CHECKS with patched constants (lambdas captured OLD values;
        # we must rebuild them using the monkeypatched attrs)
        from typing import List, Tuple

        new_checks: List[Tuple[str, callable, bool]] = [
            ("ML model: precursor_classifier.tflite",
             lambda: dr.check_file_exists(dr.ASSET_DIR / "precursor_classifier.tflite"), True),
            ("ML model: ml_anomaly_model.tflite",
             lambda: dr.check_file_exists(dr.ASSET_DIR / "ml_anomaly_model.tflite"), True),
            ("Scaler:   precursor_scaler.json",
             lambda: dr.check_json_parseable(dr.ASSET_DIR / "precursor_scaler.json"), True),
            ("Script:   run_pipeline.py",
             lambda: dr.check_file_exists(dr.SCRIPTS_DIR / "run_pipeline.py"), True),
            ("Script:   health_check.py",
             lambda: dr.check_file_exists(dr.SCRIPTS_DIR / "health_check.py"), True),
            ("Compose:  docker-compose.yml",
             lambda: dr.check_file_exists(dr.ROOT / "docker-compose.yml"), True),
            ("Compose:  docker-compose.collect.yml",
             lambda: dr.check_file_exists(dr.ROOT / "docker-compose.collect.yml"), True),
            ("Compose:  docker-compose.train.yml",
             lambda: dr.check_file_exists(dr.ROOT / "docker-compose.train.yml"), True),
        ]
        monkeypatch.setattr(dr, "CHECKS", new_checks)

        results, failures = dr.run_checks()

        # All fatal checks should pass — no false positives for files we created
        failed_labels = [r["label"] for r in results if not r["ok"] and r["fatal"]]
        assert failures == 0, (
            f"Expected 0 fatal failures for files that exist, "
            f"but got {failures}: {failed_labels}"
        )

        # Every result for a fatal check must be ok=True
        for r in results:
            if r["fatal"]:
                assert r["ok"], (
                    f"Fatal check '{r['label']}' reported FAIL for a file that exists: "
                    f"{r['detail']}"
                )
